language: node_js

node_js:
  - "6"
  - "8"
  - "10"
  - "12"

cache:
  directories:
    - node_modules

install:
  - npm install

scripts:
  - npm install codecov -g

after_success:
  - codecov

notifications:
  email: false
